apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-presentation
  namespace: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-presentation
  template:
    metadata:
      labels:
        app: test-presentation
    spec:
      containers:
        - name: test-presentation
          image: livedevkenya/test-presentation-app:latest
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              value: "http://spring-app-service.mongo-express:55702/"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: test-presentation-service
  namespace: mongo-express
spec:
  selector:
    app: test-presentation
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 80
  type: NodePort
