apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: core-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: test-spring-app:latest
          env:
            - name: MONGO_URI
              value: "mongodb://root:example@mongodb:27017"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-app
  namespace: core-app
spec:
  selector:
    app: spring-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
