apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: livedevkenya/test-spring-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              value: "root:example@mongodb-service:27017"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
  namespace: mongo-express
spec:
  selector:
    app: spring-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
