services:
  mongodb:
    image: mongo:latest
    container_name: core-database-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
    networks:
      - springboot-network
  
  mongo-express:
    image: mongo-express:latest 
    container_name: core-mongo-express 
    restart: always 
    ports: 
      - 8081:8081 
    environment: 
      ME_CONFIG_MONGODB_ADMINUSERNAME: root 
      ME_CONFIG_MONGODB_ADMINPASSWORD: example 
      ME_CONFIG_MONGODB_SERVER: core-database-mongo
    depends_on:
      - mongodb
    networks:
      - springboot-network

  spring-app:
    image: test-spring-app:latest
    container_name: core-test-spring
    restart: always
    build: ../src/backend/core
    ports:
      - 8080:8080
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongodb
    networks:
      - springboot-network

  test-presentation:
    image: test-presentation-app:latest
    container_name: core-test-angular
    restart: always
    build: ../src/frontend/test-presentation
    ports:
      - 4200:80
    environment:
      - API_URL=${API_URL}
    depends_on:
      - spring-app
    networks:
      - springboot-network

volumes:
  mongodb-data:
    driver: local
  mongodb-config:
    driver: local
networks:
  springboot-network:
    driver: bridge