# Use an official Node.js runtime as a build stage
FROM node:22 AS build

# Set the working directory
WORKDIR /app

# Copy the Angular project files
COPY package.json package-lock.json ./
RUN npm install
COPY . .

# Build the Angular app
RUN npm run build --prod

# Use Nginx to serve the Angular app
FROM nginx:1.25-alpine

# Remove default Nginx HTML files
RUN rm -rf /usr/share/nginx/html/*

# Copy built Angular files to Nginx
COPY --from=build /app/dist/test-presentation/browser /usr/share/nginx/html

# Copy the environment replacement script
COPY set-env.sh /usr/share/nginx/html/set-env.sh
RUN chmod +x /usr/share/nginx/html/set-env.sh

# Expose the Nginx port
EXPOSE 80

# Run the script to replace the API URL and start Nginx
CMD ["/bin/sh", "-c", "/usr/share/nginx/html/set-env.sh && nginx -g 'daemon off;'"]
