name: Build and Push Spring Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    env:
      REGISTRY: docker.io
      REPOSITORY: livedevkenya  # Replace with your username or organization
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      MONGO_URI: mongodb://root:example@core-database-mongo:27017
      API_URL: http://core-test-spring:8080

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up JDK 17 
        uses: actions/setup-java@v2
        with: 
          java-version: '17'
          distribution: 'adopt'

      - name: Build Spring Boot application 
        run: | 
          cd ./src/backend/core 
          mvn compile

      - name: Log in to Docker Registry
        run: echo "${{ env.DOCKER_PASSWORD }}" | docker login ${{ env.REGISTRY }} -u ${{ env.DOCKER_USERNAME }} --password-stdin

      - name: Build Test Spring Image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/test-spring-app:latest ./src/backend/core
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/test-spring-app:latest

      - name: Log out from Docker Registry
        run: docker logout
